apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgpool
  namespace: myproject
  labels:
    node-name: pgpool
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      node-name: pgpool
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        node-name: pgpool
    spec:
      containers:
      - image: mcyprian/pgpool-fedora30:latest
        command: ["run-pgpool", "-n"]
        name: pgpool
        imagePullPolicy: Always
        ports:
        - containerPort: 9999
          name: pgpool
          protocol: TCP
        env:
        - name: POSTGRESQL_USER
          value: user
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-cluster
              key: database-password
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        resources:
          limits:
            cpu: 600m
            memory: 500M
          requests:
            cpu: 100m
            memory: 250M
