apiVersion: v1
kind: Service
metadata:
  name: pgpool
  namespace: myproject
  labels:
    node-name: pgpool
spec:
  selector:
    node-name: pgpool
  ports:
  - port: 9999
    protocol: TCP
    targetPort: 9999
